### ISSUE TITLE
[BUG] バグ報告

### ISSUE THREAD

**Issue by kinoko2k** [Akkey57492/AkkeyBot#1]
**バグの詳細**
searchでは

**バグの再現手順**
バグを起こすための手順を記載してください。
(箇条書きが最適です。)

**スクリーンショット**
![76E8E785-CFF6-44B4-8E8E-8F25ABE9D17E](https://user-images.githubusercontent.com/65443692/144385714-e0b37424-3388-4ba5-bb41-fe0bf5fccbce.jpeg)

**Comment by Akkey57492** [comment]
1.2.2-b1で修正済み
